# Generated by Django 6.1 on 2026-08-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Peso (kg)')),
                ('unidad', models.CharField(default='kg', max_length=10, verbose_name='Unidad')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Registro activo')),
            ],
            options={
                'verbose_name': 'Registro de peso',
                'verbose_name_plural': 'Registros de pesos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
