# Generated by Django 6.1 on 2026-09-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('curp', models.CharField(blank=True, max_length=18, null=True, verbose_name='CURP')),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('puesto', models.CharField(choices=[('ADMIN', 'Administrador'), ('GERENTE', 'Gerente'), ('SUPERVISOR', 'Supervisor'), ('VENDEDOR', 'Vendedor'), ('ALMACEN', 'Almacenista'), ('CONDUCTOR', 'Conductor'), ('OPERADOR', 'Operador'), ('SOPORTE', 'Soporte Técnico'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Puesto')),
                ('fecha_contratacion', models.DateField(verbose_name='Fecha de contratación')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario')),
                ('nss', models.CharField(blank=True, max_length=20, null=True, verbose_name='NSS')),
                ('numero_empleado', models.CharField(max_length=20, unique=True, verbose_name='Número de empleado')),
                ('activo', models.BooleanField(default=True, verbose_name='Empleado activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
    ]
