# Generated by Django 6.1 on 2026-09-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['numero_empleado'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='curp',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_contratacion',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='nss',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='rfc',
        ),
        migrations.AddField(
            model_name='empleado',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_empleado',
            field=models.CharField(editable=False, max_length=10, unique=True, verbose_name='Número de empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Puesto'),
        ),
    ]
